//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemRequest()
        {
            this.ItemReleases = new HashSet<ItemRelease>();
            this.ItemRequestDetails = new HashSet<ItemRequestDetail>();
        }
    
        public int Id { get; set; }
        public int DocumentSetupId { get; set; }
        public int DepartmentId { get; set; }
        public int EmployeeId { get; set; }
        public int FiscalYearId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> DocumentNo { get; set; }
        public string DisplayDocumentNo { get; set; }
        public string Remarks { get; set; }
        public int ReleasedType { get; set; }
        public Nullable<int> AcceptedBy { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<int> ItemReceivedBy { get; set; }
        public Nullable<System.DateTime> ItemReceivedDate { get; set; }
        public int ApplicationStatus { get; set; }
        public string DisplayRegistrationNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DocumentSetup DocumentSetup { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRelease> ItemReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestDetail> ItemRequestDetails { get; set; }
    }
}
