//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationRate
    {
        public int Id { get; set; }
        public int FiscalYearId { get; set; }
        public int ItemGroupId { get; set; }
        public decimal Rate { get; set; }
    
    	//RelationshipName: FK_DepreciationRate_FiscalYear
        public virtual FiscalYear FiscalYear { get; set; }
    	//RelationshipName: FK_DepreciationRate_ItemGroup
        public virtual ItemGroup ItemGroup { get; set; }
    }
}
