//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequestDetail
    {
        public int Id { get; set; }
        public int ItemRequestId { get; set; }
        public int ItemId { get; set; }
        public int Qty { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> ItemReleaseId { get; set; }
        public string Remarks { get; set; }
        public string Specification { get; set; }
    
    	//RelationshipName: FK_ItemRequestDetail_Item
        public virtual Item Item { get; set; }
    	//RelationshipName: FK_ItemRequestDetail_ItemRelease
        public virtual ItemRelease ItemRelease { get; set; }
    	//RelationshipName: FK_ItemRequestDetail_ItemRequest
        public virtual ItemRequest ItemRequest { get; set; }
    	//RelationshipName: FK_ItemRequestDetail_PurchaseOrder
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
