//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetLog
    {
        public int Id { get; set; }
        public Nullable<int> AppUserId { get; set; }
        public string Guid { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsUsed { get; set; }
        public string Browser { get; set; }
        public string Device { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string ResetBrowser { get; set; }
        public string ResetDevice { get; set; }
        public string ResetIPAddress { get; set; }
    }
}
