//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int PermissionId { get; set; }
    
    	//RelationshipName: FK_RoleModulePermission_Permission
        public virtual Permission Permission { get; set; }
    	//RelationshipName: FK_RoleModulePermission_Role
        public virtual Role Role { get; set; }
    }
}
