//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransactionDetail
    {
        public int Id { get; set; }
        public int StockTransactionId { get; set; }
        public int ItemId { get; set; }
        public string ItemSubCodeNo { get; set; }
        public string LedgerPageNo { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int StockEffect { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal PurchaseAmount { get; set; }
    
    	//RelationshipName: FK_StockTransactionDetail_Department
        public virtual Department Department { get; set; }
    	//RelationshipName: FK_StockTransactionDetail_Employee
        public virtual Employee Employee { get; set; }
    	//RelationshipName: FK_StockTransactionDetail_Item
        public virtual Item Item { get; set; }
    	//RelationshipName: FK_StockTransactionDetail_StockTransaction
        public virtual StockTransaction StockTransaction { get; set; }
    }
}
