//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftIms.Data.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AppUsers = new HashSet<AppUser>();
            this.ItemReleases = new HashSet<ItemRelease>();
            this.ItemRequests = new HashSet<ItemRequest>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.StockTransactions = new HashSet<StockTransaction>();
            this.StockTransactionDetails = new HashSet<StockTransactionDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string EmployeeType { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_AppUser_Employee
        public virtual ICollection<AppUser> AppUsers { get; set; }
    	//RelationshipName: FK_Employee_Department
        public virtual Department Department { get; set; }
    	//RelationshipName: FK_Employee_Designation
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_ItemRelease_Employee
        public virtual ICollection<ItemRelease> ItemReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_ItemRequest_Employee
        public virtual ICollection<ItemRequest> ItemRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_PurchaseOrder_Employee
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_StockTransaction_Employee
        public virtual ICollection<StockTransaction> StockTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//RelationshipName: FK_StockTransactionDetail_Employee
        public virtual ICollection<StockTransactionDetail> StockTransactionDetails { get; set; }
    }
}
